### ISSUE TITLE
Wrong checking of FileReader 

### ISSUE THREAD

**Issue by tcorral** [s3u/har-view#6]
Hi.
You are checking this in your HTML code:

```
if(typeof FileReader !== "undefined") 
{
    alert('Oops - your browser does not support FileReader. Use latest Chrome or Firefox');
}
```

Maybe you must check if FileReader is undefined.

I have Google Chrome 16.0.912.63.

Thanks and good job!

**Comment by s3u** [comment]
Thanks for noticing the error.
